- hosts: all
  tasks:
    - name: stop container
      shell:  docker container stop project                    #name of container 
    - name: remove container
      shell: docker container rm project
    - name: remove docker image
      shell: docker image rm sakir2141/project                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name project -p 9000:80 sakir2141/project     #(docker-job>> name of jenkins job)
